// <auto-generated />
namespace EClerx.MVC.Day26.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class NewRowToBook : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(NewRowToBook));
        
        string IMigrationMetadata.Id
        {
            get { return "202207270559523_NewRowToBook"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
